animes = [
  {
    "id": 1,
    "titulo": "Gintama",
    "categoria": "Action, Aventura, Shounen",
    "rating": "91%",
    "reviews": 33682,
    "season": "Winter",
    "tipo": "Movie",
    "poster": "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/4fadd5f113c28de1b22d4ef67a78890b.jpe",
  },
  {
    "id": 2,
    "titulo": "Steins;Gate",
    "categoria": "Drama, Psychological, Sci-fi, Thriller",
    "rating": "89%",
    "reviews": 410803,
    "season": "Spring",
    "tipo": "TV Show",
    "poster": "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/4fadd5f113c28de1b22d4ef67a78890b.jpe",
  },
  {
    "id": 3,
    "titulo": "One Piece",
    "categoria": "Action, Adventure, Comedy, Drama",
    "rating": "87%",
    "reviews": 455939,
    "season": "Airing since 1999",
    "tipo": "TV Show",
    "poster": "https://static.wikia.nocookie.net/doblaje/images/8/8d/One_Piece.png/revision/latest/thumbnail/width/360/height/450?cb=20190727212440&path-prefix=es",
  },
  {
    "id": 4,
    "titulo": "Made in Abyss",
    "categoria": "Adventure, Drama, Fantasy, Horror",
    "rating": "85%",
    "reviews": 272553,
    "season": "Summer",
    "tipo": "TV Show",
    "poster": "https://www.crunchyroll.com/imgsrv/display/thumbnail/480x720/catalog/crunchyroll/dc21faacccb89df40fff14f7e0e1ff00.jpe",
  },
  {
    "id": 5,
    "titulo": "Violet Evergarden Movie",
    "categoria": "Drama, Fantasy, Slice of life",
    "rating": "88%",
    "reviews": 126076,
    "season": "Summer",
    "tipo": "Movie",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTcyMzhlMjgtNDE0ZS00NTJiLWJiZjEtZTIxM2JkMjM5M2UzXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_.jpg",
  },
]
